Add support for Nextcloud 25
nextcloud/calendar_resource_management pull request #50
Opened 2022-05-09 15:13 UTC by st3iny

Signed-off-by: Richard Steinmetz <richard@steinmetz.cloud>

2022-05-09 15:42 UTC, tcitworld approved these changes

2022-05-09 17:59 UTC, ChristophWurst approved these changes

2022-05-09 17:59 UTC, ChristophWurst requested changes
Please add stable24 to the test setup matrix

2022-05-10 07:33 UTC, ChristophWurst approved these changes

2022-05-10 07:33 UTC, merged